name: Update database

on:
  schedule:
    # 毎週火曜日5:00に実行(UTC) 
    - cron:  '0 0 5 * MON'
  push:
    branches:
      - main

jobs:
  update-database:
    runs-on: ubuntu-latest
    name: Update database 
    environment: production
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Push
      env:
            FIREBASE_ADMIN_PROJECT_ID: ${{ secrets.FIREBASE_ADMIN_PROJECT_ID }}
            FIREBASE_ADMIN_PRIVATE_KEY: ${{ secrets.FIREBASE_ADMIN_PRIVATE_KEY }}
            FIREBASE_ADMIN_CLIENT_EMAIL: ${{ secrets.FIREBASE_ADMIN_CLIENT_EMAIL }}
            DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
      run: |
        yarn install
        yarn push