name: Update database

on:
  schedule:
    # 毎週火曜日5:00に実行(UTC) 
    - cron:  '0 0 5 * MON'
  push:
    branches:
      - main

jobs:
  update-database:
    runs-on: ubuntu-latest
    name: Update database 
    environment: production
    steps:
    - uses: actions/checkout@v3
    - name: Set ENV
      run: |
        echo "FIREBASE_ADMIN_PROJECT_ID=$FIREBASE_ADMIN_PROJECT_ID" >> .env
        echo "FIREBASE_ADMIN_PRIVATE_KEY=$FIREBASE_ADMIN_PRIVATE_KEY" >> .env
        echo "FIREBASE_ADMIN_CLIENT_EMAIL=$FIREBASE_ADMIN_CLIENT_EMAIL" >> .env
        echo "DEEPL_API_KEY=$DEEPL_API_KEY" >> .env
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Push
      run: |
        yarn install
        yarn push